name: Hello world
on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Call the action
        uses: ./
        with:
          ref: ${{ github.sha }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ruby-github-action-template
          owner: matiasalbarello
